Repository Alejandrox666/DesWebIntegral_AHN_SVC, pull requests merged in 2025-05, with the labels that each got.

#6 Funcionalidad register
  register.txt
Labels: documentation

#8 Componente Chat
  especialista/chat/chat.component.css
  especialista/chat/chat.component.html
  especialista/chat/chat.component.spec.ts
  especialista/chat/chat.component.ts
  especialista/formularios/formularios.component.css
  especialista/formularios/formularios.component.html
  especialista/formularios/formularios.component.spec.ts
  especialista/formularios/formularios.component.ts
Labels: documentation

#9 Componente navbar
  especialista/navbar/navbar.component.css
  especialista/navbar/navbar.component.html
  especialista/navbar/navbar.component.spec.ts
  especialista/navbar/navbar.component.ts
Labels: bug, documentation

#10 Navbar
  administrador/Tabla de visualización/Visualización.txt
  administrador/navbar/navbar.txt
Labels: bug
